### ISSUE TITLE
mail error maybe 

### ISSUE THREAD

**Issue by relic-yuexi** [zyushun/zyushun.github.io#1]
https://github.com/zyushun/zyushun.github.io/blob/3ac95b886e22d737183bdc27ebf088ac45e13120/index.jemdoc#L11

yushunzhang@link.cuhk.edu.cn

**Comment by zyushun** [comment]
Hi @relic-yuexi ,

Thanks for the suggestions, but I wrote in that way to avoid spam :)

Yushun
